GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Task12"
}

###

DELETE http://localhost:3001/todo/delete/6418e0f9041af7acbe154f44

###

PUT http://localhost:3001/todo/complete/64168049e10345d6a8c428ec